// Mock database for development when DATABASE_URL is not set
export const mockQuizzes = {
  CLASS_10: {
    id: "mock-quiz-class-10",
    title: "Class 10th Career Guidance Quiz",
    description: "Choose your perfect stream after 10th grade - Science, Commerce, or Arts",
    forLevel: "CLASS_10" as const,
    questions: [
      // RIASEC Interest Questions for Class 10
      {
        id: "q1",
        orderIndex: 1,
        text: "How much do you enjoy working with numbers and calculations?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "C",
        weight: 1,
      },
      {
        id: "q2", 
        orderIndex: 2,
        text: "How interested are you in conducting science experiments?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "I",
        weight: 1,
      },
      {
        id: "q3",
        orderIndex: 3,
        text: "How much do you enjoy creative writing or art projects?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "A",
        weight: 1,
      },
      {
        id: "q4",
        orderIndex: 4,
        text: "How much do you like helping classmates with their studies?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "S",
        weight: 1,
      },
      {
        id: "q5",
        orderIndex: 5,
        text: "How much do you enjoy organizing school events or leading groups?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "E",
        weight: 1,
      },
      {
        id: "q6",
        orderIndex: 6,
        text: "How much do you enjoy working with tools or fixing things?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "R",
        weight: 1,
      },
      // Basic Aptitude Questions for Class 10
      {
        id: "q7",
        orderIndex: 7,
        text: "What is 25% of 200?",
        options: ["40", "50", "60", "75"],
        topicTag: "numerical",
        weight: 1,
        correctOptionIndex: 1,
      },
      {
        id: "q8",
        orderIndex: 8,
        text: "Which word means the same as 'happy'?",
        options: ["Sad", "Joyful", "Angry", "Tired"],
        topicTag: "verbal",
        weight: 1,
        correctOptionIndex: 1,
      },
      {
        id: "q9",
        orderIndex: 9,
        text: "What comes next: 2, 4, 6, 8, ?",
        options: ["9", "10", "12", "14"],
        topicTag: "logical",
        weight: 1,
        correctOptionIndex: 1,
      },
      {
        id: "q10",
        orderIndex: 10,
        text: "If you fold a square in half, how many sides does it have?",
        options: ["2", "4", "6", "8"],
        topicTag: "spatial",
        weight: 1,
        correctOptionIndex: 1,
      },
    ]
  },
  CLASS_12: {
    id: "mock-quiz-class-12",
    title: "Class 12th Career & College Guidance Quiz",
    description: "Discover your ideal career path and college options after 12th grade",
    forLevel: "CLASS_12" as const,
    questions: [
      // RIASEC Interest Questions for Class 12
      {
        id: "q1",
        orderIndex: 1,
        text: "How much do you enjoy analyzing complex problems and finding solutions?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "I",
        weight: 1,
      },
      {
        id: "q2", 
        orderIndex: 2,
        text: "How interested are you in managing finances or business operations?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "E",
        weight: 1,
      },
      {
        id: "q3",
        orderIndex: 3,
        text: "How much do you enjoy creating digital content or multimedia projects?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "A",
        weight: 1,
      },
      {
        id: "q4",
        orderIndex: 4,
        text: "How much do you like mentoring or teaching others?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "S",
        weight: 1,
      },
      {
        id: "q5",
        orderIndex: 5,
        text: "How much do you enjoy working with data and maintaining records?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "C",
        weight: 1,
      },
      {
        id: "q6",
        orderIndex: 6,
        text: "How much do you enjoy hands-on technical work or engineering projects?",
        options: ["Not at all", "A little", "Moderately", "Very much"],
        topicTag: "R",
        weight: 1,
      },
      // Advanced Aptitude Questions for Class 12
      {
        id: "q7",
        orderIndex: 7,
        text: "If a shirt costs ₹1200 and is sold at a 20% discount, what is the selling price?",
        options: ["₹960", "₹1000", "₹1040", "₹1080"],
        topicTag: "numerical",
        weight: 1,
        correctOptionIndex: 0,
      },
      {
        id: "q8",
        orderIndex: 8,
        text: "Complete the analogy: Doctor is to Hospital as Teacher is to:",
        options: ["School", "Library", "Office", "Laboratory"],
        topicTag: "verbal",
        weight: 1,
        correctOptionIndex: 0,
      },
      {
        id: "q9",
        orderIndex: 9,
        text: "What comes next in the sequence: 1, 4, 9, 16, ?",
        options: ["20", "25", "30", "36"],
        topicTag: "logical",
        weight: 1,
        correctOptionIndex: 1,
      },
      {
        id: "q10",
        orderIndex: 10,
        text: "If you rotate a rectangle 90 degrees clockwise, what shape do you get?",
        options: ["Same rectangle", "Square", "Different rectangle", "Circle"],
        topicTag: "spatial",
        weight: 1,
        correctOptionIndex: 2,
      },
    ]
  }
};

// For backward compatibility
export const mockQuiz = mockQuizzes.CLASS_10;
